### ISSUE TITLE
boot.img unknown ramdisk

### ISSUE THREAD

**Issue by scafroglia93** [bq/aquaris-M10-FHD#1]
My ramdisk extractor provide me this message:

"ramdisk is unknown format,can't unpack ramdisk"

Can you provide me a boot.img with ramdisk for boot my custom kernel please otherwise it's useless share the kernel . Keep me updated guys .)

**Comment by Kra1o5** [comment]
Hello @scafroglia93,

Here we provide kernel source under GPL to build zImage.

Greetings

**Comment by scafroglia93** [comment]
I saw and this has honored you have fewer and fewer companies which open their resources. The problem is that I can not remove the ramdisk. I could contact in private, maybe we find the solution

**Comment by Kra1o5** [comment]
Hello @scafroglia93,

You can contact us via email at opensource@bq.com

Greetings

**Comment by scafroglia93** [comment]
My work (fully functional for this tab)

https://github.com/CasualsKernelProject/freezerfhd/commits/rebase
